
services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: tasktracker-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - tasktracker-data:/var/lib/postgresql/data

volumes:
  tasktracker-data: